/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_polymehr_polyCmd_util_LinuxUtil */

#ifndef _Included_me_polymehr_polyCmd_util_LinuxUtil
#define _Included_me_polymehr_polyCmd_util_LinuxUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_polymehr_polyCmd_util_LinuxUtil
 * Method:    getTerminalColumns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_polymehr_polyCmd_util_LinuxUtil_getTerminalColumns
  (JNIEnv *, jclass);

/*
 * Class:     me_polymehr_polyCmd_util_LinuxUtil
 * Method:    getTerminalLines
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_polymehr_polyCmd_util_LinuxUtil_getTerminalLines
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
