/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_polymehr_polyCmd_util_Unix */

#ifndef _Included_me_polymehr_polyCmd_util_Unix
#define _Included_me_polymehr_polyCmd_util_Unix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_polymehr_polyCmd_util_Unix
 * Method:    getTerminalColumns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_polymehr_polyCmd_util_Unix_getTerminalColumns
  (JNIEnv *, jclass);

/*
 * Class:     me_polymehr_polyCmd_util_Unix
 * Method:    getTerminalLines
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_polymehr_polyCmd_util_Unix_getTerminalLines
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
